### ISSUE TITLE
Example handler?

### ISSUE THREAD

**Issue by JosiahParry** [mdneuzerling/r-on-lambda#3]
I am trying to understand this code to implement it myself.

One of the parts that I am unclear on is the `_HANDLER`. It appears that it somehow identifies the R functions that exist in `functions.R`. The `runtime.R` calls `Sys.getenv("_HANDLER")` however there is not an `.Renviron` file to go along with it. Are you able to provide an example value or explain a bit more how it works? 

Thanks!

**Comment by mdneuzerling** [comment]
Hi Josiah. [That environment variable is managed by AWS itself](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html), based on user configuration. It's of the form “file.function”. So in my example, I put the code for my `parity` function in a file called `functions.R`, so my handler will be “functions.parity”. You can set the handler either as the CMD of the Dockerfile (eg. `CMD [ "functions.parity" ]`) or through the AWS Lambda console (which takes precedence).

**Comment by JosiahParry** [comment]
Apologies for the barrage! The blog post is a bit out of data / using a different API so I'm just reading your code and hoping for the best. 

If you'd humor me, the next piece I'm stuck on is understanding how any data is received and passed to the handler function. My confusion lies in that we are only waiting for a GET request which has no body. 

https://github.com/mdneuzerling/r-on-lambda/blob/9769849565a9e4d1561101e2a67eaa8958567892/runtime.R#L180

How is the `invocation/next` endpoint able to inform the handler?

**Comment by mdneuzerling** [comment]
Not at all! The blog post is definitely out-of-date, and my knowledge was pretty basic to begin with. Unfortunately there doesn't seem to be a whole lot of content out there otherwise.

I try to imagine it as AWS taking the Docker image and putting a whole bunch of other stuff on top of it. So:
1. Based on user configuration, AWS sets the `_HANDLER` environment variable. R code retrieves the `_HANDLER` environment variable and from it determines the `file` and `function`. After this point the `_HANDLER` isn't needed. R only uses this information to determine what function to use to deal with the inputs, and where to find that function.
3. For each Lambda instance, AWS sets up a `AWS_LAMBDA_RUNTIME_API` environment variable. R code uses this to determine the `next_invocation_endpoint` and `response_endpoint` endpoints for the Lambda instance.
4. R queries the `next_invocation_endpoint` endpoint asking for the next input that it needs to parse. This `GET` request hangs indefinitely until AWS receives input for the Lambda, which it passes to R as a response to that `GET` request. This is the bit where R is waiting indefinitely for something to happen, like someone querying the Lambda through an API gateway. So if no one uses the Lambda then R will wait around for a response to that request until AWS shuts down the Lambda instance for inactivity.
5. Once the input is made available through that `next_invocation_endpoint` endpoint, the `handle_event` R function takes over. This is arguably where the code is most fragile, as it has to extract and parse the input from the response to that `GET` request. This means extracting function arguments, headers, etc.
6. If everything goes well, R calculates the response from the inputs given in the response body and then `POST`s the result to the `response_endpoint`.
7. R returns to step 4, and awaits the next input from the `next_invocation_endpoint`

**Comment by mdneuzerling** [comment]
Actually, just thinking on this, there's no reason that the handler _must_ be `file.function`. It could be anything, since it's interpreted by R, although it's probably used in logging and metrics somewhere. I think a more natural handler would be function name only. Then R can source a bunch of files and do `call(handler, ...)`.
